include("${CMAKE_INSTALL_LIBDIR}/cmake/fgal-targets.cmake")
set(fgal_INCLUDE_DIRS "${CMAKE_INSTALL_PREFIX}/include")

set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_LIBDIR}")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)